pool:
  name: Arm64
  vmImage: 'ubuntu-22.04'

trigger:
- main
resources:
- repo: self
variables:
  imagePullSecret: 'regcred'

stages:
- stage: Build
  displayName: "Build and Push Docker Images"
  jobs:
  - job: BuildAndPush
    displayName: "Build and Push Docker Images"
    pool:
      name: Arm64
      vmImage: 'ubuntu-22.04'
    steps:
    - task: DockerInstaller@0
      displayName: "Install Docker CLI"
  
    - script: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk
        echo "##vso[task.setvariable variable=JAVA_HOME]$(readlink -f /usr/bin/java | sed "s:bin/java::")"
        echo "Java 8 installed successfully"
      displayName: 'Install Java 8'

    - script: |
         cd publisher
         chmod +x ./gradlew
         ./gradlew clean build -x test
      displayName: "Build Publisher Project"
    
    - task: Docker@2
      displayName: "Build and Push Publisher Image"
      inputs:
        containerRegistry: 'DockerConnection'
        command: "buildAndPush"
        repository: 'manoelvsneto/DaprJavaPublisher'
        Dockerfile: '$(Build.SourcesDirectory)/**/publisher/Dockerfile'
        arguments: "--platform linux/arm64"
        tags:  $(Build.BuildId)
    
    - script: |
         cd subscriber
         chmod +x ./gradlew
         ./gradlew clean build -x test
      displayName: "Build Subscriber Project"
    - task: Docker@2
      displayName: "Build and Push Subscriber Image"
      inputs:
        containerRegistry: 'DockerConnection'
        command: "buildAndPush"
        repository: 'manoelvsneto/DaprJavaSubscriber'
        Dockerfile: '$(Build.SourcesDirectory)/**/subscriber/Dockerfile'
        arguments: "--platform linux/arm64"
        tags:  $(Build.BuildId)
        
    - task: KubernetesManifest@0
      displayName: Create imagePullSecret
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        action: createSecret
        secretName: $(imagePullSecret)
        dockerRegistryEndpoint: 'DockerConnection'

    - task: KubernetesManifest@0
      displayName: "Deploy publisher"
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        action: deploy
        manifests: |
          $(Build.SourcesDirectory)/**/publisher/publisher-deployment.yaml
          $(Build.SourcesDirectory)/**/publisher/publisher-service.yaml
        containers: 'manoelvsneto/daprjavapublisher:$(Build.BuildId)'

    - task: KubernetesManifest@0
      displayName: "Deploy subscriber"
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        action: deploy
        manifests: |
          $(Build.SourcesDirectory)/**/subscriber/subscriber-deployment.yaml
          $(Build.SourcesDirectory)/**/subscriber/subscriber-service.yaml
        containers: 'manoelvsneto/daprjavasubscriber:$(Build.BuildId)'
    - task: KubernetesManifest@0
      displayName: "Deploy"
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        action: deploy
        manifests: |
          $(Build.SourcesDirectory)/**/ingress/ingress.yaml
          $(Build.SourcesDirectory)/**/redis/redis-deployment.yaml
          $(Build.SourcesDirectory)/**/redis/redis-service.yaml