pool:
  name: Arm64
  vmImage: 'ubuntu-22.04'

trigger:
- main
resources:
- repo: self
variables:
  imagePullSecret: 'regcred'

stages:
- stage: Build
  displayName: "Build and Push Docker Images"
  jobs:
  - job: BuildAndPush
    displayName: "Build and Push Docker Images"
    pool:
      name: Arm64
      vmImage: 'ubuntu-22.04'
    steps:
    - task: DockerInstaller@0
      displayName: "Install Docker CLI"
      condition: 
    
    - task: Docker@2
      displayName: "Build and Push Publisher Image"
      inputs:
        containerRegistry: 'DockerConnection'
        command: "buildAndPush"
        repository: 'manoelvsneto/DaprJavaPublisher'
        Dockerfile: '$(Build.SourcesDirectory)/publisher/Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  displayName: "Deploy to Kubernetes"
  dependsOn: Build
  jobs:
  - deployment: DeployKubernetes
    displayName: "Deploy"
    environment: "prod"
  
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              kubernetesServiceConnection: K8SOracleCloud
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: 'DockerConnection'

          - task: KubernetesManifest@0
            displayName: "Deploy Redis"
            inputs:
              manifests: |
                kubernetes/redis/redis-deployment.yaml
                kubernetes/redis/redis-service.yaml

          - task: KubernetesManifest@0
            displayName: "Deploy Publisher"
            inputs:
              manifests: |
                kubernetes/publisher/publisher-deployment.yaml
                kubernetes/publisher/publisher-service.yaml
              containers: |
                manoelvsneto/DaprJavaPublisher:$(Build.BuildId) 
                

          - task: KubernetesManifest@0
            displayName: "Deploy Ingress"
            inputs:
              manifests: |
                kubernetes/ingress/ingress.yaml
