apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: "localhost:6379" # Endereço do Redis
    - name: redisPassword
      value: "" # Senha do Redis, se aplicável