apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: publisher.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: publisher
            port:
              number: 8081
  - host: subscriber.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: subscriber
            port:
              number: 8080
